/**
 * Upload Jaipurio product/brand media to Cloudinary as WebP (images) / optimized video.
 * Usage: node scripts/uploadJaipurioMedia.js
 */
require('dotenv').config();
const path = require('path');
const fs = require('fs');
const cloudinary = require('cloudinary').v2;

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const PUBLIC_DIR = path.join(__dirname, '..', '..', 'frontend', 'public');
const OUT_JS = path.join(__dirname, '..', '..', 'frontend', 'src', 'data', 'cloudinaryMedia.js');
const OUT_JSON = path.join(__dirname, 'jaipurio-media-map.json');

const IMAGE_FILES = [
  'matka.png',
  'kulhad.png',
  'planter.png',
  'diya.png',
  'elephant.png',
  'camel.png',
  'jaipurio_banner.png',
  'jaipurio_banner_art.png',
  'jaipurio_banner_clean.png',
  'jaipurio_home_banner.jpg',
  'jaipurio_logo.png',
  'jaipurio_logo_bg.png',
  'jaipurio_logo_header.png',
  'jaipurio_logo_sidebar.png',
  'splash.png',
  'login_hero_1.png',
  'login_hero_2.png',
  'favicon.png',
  'logo.png',
  'admin_logo.png',
];

const VIDEO_FILES = [
  'splash.mp4',
  'top_banner_video.mp4',
  'generate_a_simple_video_for_th.mp4',
  'thoda_camel_movement_fast_kro.mp4',
];

const toWebpDelivery = (url) => {
  if (!url || !url.includes('/upload/')) return url;
  return url.replace('/upload/', '/upload/f_webp,q_auto:good,c_limit,w_1600/');
};

const uploadImage = async (fileName) => {
  const filePath = path.join(PUBLIC_DIR, fileName);
  if (!fs.existsSync(filePath)) {
    console.warn(`SKIP missing image: ${fileName}`);
    return null;
  }
  const publicId = `jaipurio/${path.parse(fileName).name}`;
  console.log(`Uploading image ${fileName} → ${publicId}`);
  const result = await cloudinary.uploader.upload(filePath, {
    public_id: publicId,
    folder: undefined,
    overwrite: true,
    resource_type: 'image',
    format: 'webp',
    quality: 'auto:good',
    transformation: [{ width: 2000, crop: 'limit', fetch_format: 'webp', quality: 'auto:good' }],
  });
  return toWebpDelivery(result.secure_url);
};

const uploadVideo = async (fileName) => {
  const filePath = path.join(PUBLIC_DIR, fileName);
  if (!fs.existsSync(filePath)) {
    console.warn(`SKIP missing video: ${fileName}`);
    return null;
  }
  const publicId = `jaipurio/video/${path.parse(fileName).name}`;
  console.log(`Uploading video ${fileName} → ${publicId}`);
  const result = await cloudinary.uploader.upload(filePath, {
    public_id: publicId,
    overwrite: true,
    resource_type: 'video',
    quality: 'auto:eco',
  });
  return result.secure_url;
};

const run = async () => {
  if (!process.env.CLOUDINARY_CLOUD_NAME || !process.env.CLOUDINARY_API_KEY) {
    throw new Error('Cloudinary credentials missing in backend/.env');
  }

  const map = { images: {}, videos: {} };

  for (const file of IMAGE_FILES) {
    try {
      const url = await uploadImage(file);
      if (url) map.images[`/${file}`] = url;
    } catch (err) {
      console.error(`FAIL image ${file}:`, err.message);
    }
  }

  for (const file of VIDEO_FILES) {
    try {
      const url = await uploadVideo(file);
      if (url) map.videos[`/${file}`] = url;
    } catch (err) {
      console.error(`FAIL video ${file}:`, err.message);
    }
  }

  fs.writeFileSync(OUT_JSON, JSON.stringify(map, null, 2));

  const js = `/** Auto-generated by backend/scripts/uploadJaipurioMedia.js — Jaipurio Cloudinary WebP/video map */
export const CLOUDINARY_IMAGES = ${JSON.stringify(map.images, null, 2)};

export const CLOUDINARY_VIDEOS = ${JSON.stringify(map.videos, null, 2)};

/** Resolve a local public path (e.g. /matka.png) to Cloudinary WebP URL when available. */
export function mediaUrl(localPath) {
  if (!localPath) return '';
  if (/^https?:\\/\\//i.test(localPath)) return localPath;
  const key = localPath.startsWith('/') ? localPath : \`/\${localPath}\`;
  return CLOUDINARY_IMAGES[key] || CLOUDINARY_VIDEOS[key] || localPath;
}

export default CLOUDINARY_IMAGES;
`;
  fs.writeFileSync(OUT_JS, js);
  console.log(`\nWrote ${OUT_JS}`);
  console.log(`Images: ${Object.keys(map.images).length}, Videos: ${Object.keys(map.videos).length}`);
};

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
